set(CMAKE_SYSTEM Windows)
set(MINGW_PATH "D:/Program Files/mingw64")

set(CMAKE_C_COMPLIER ${MINGW_PATH}/bin/gcc.exe)
set(CMAKE_CXX_COMPLIER ${MINGW_PATH}/bin/g++.exe)

set(CMAKE_FIND_ROOT_PATH ${MINGW_PATH}/x86_64-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)